server:
  port: ${SERVER_PORT:8090}
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_vendor?createDatabaseIfNotExist=true
    username: root
    password: 12345
  jpa:
    hibernate:
      ddl-auto: create



